name: CI

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install dependencies
        run: sudo apt-get install -y libsfml-dev libxrandr-dev libxcursor-dev libudev-dev libfreetype-dev libopenal-dev libflac-dev libvorbis-dev libgl1-mesa-dev libegl1-mesa-dev

      - name: Cache CMake dependencies
        uses: actions/cache@v4
        with:
          path: build/_deps
          key: ${{ runner.os }}-catch2-${{ hashFiles('tests/CMakeLists.txt') }}

      - name: Configure
        run: cmake -S . -B build -DBUILD_SHARED_LIBS=OFF "-DCMAKE_POLICY_VERSION_MINIMUM=3.5" -DBUILD_TESTS=ON -DCMAKE_CXX_FLAGS="-Wno-error"

      - name: Build
        run: cmake --build build --parallel

      - name: Test
        run: ctest --test-dir build -C Debug --output-on-failure